export enum ErrorCode {
    MATCH_NOT_FOUND = 'match_not_found',
    SALE_NOT_FOUND = 'sale_not_found',
    UNKNOWN_COMPETITION = 'unknown_competition',
    MATCH_CREATION_FAILED = 'match_creation_failed',
    COULD_NOT_LOAD_MATCHES = 'could_not_load_matches',
    INTERNAL_ERROR = 'internal_error',
    EMAIL_ALREADY_EXISTS = 'email_already_exists',
    SALE_AFTER_KICKOFF = 'sale_after_kickoff',
    SEASON_PASS_NOT_FOUND = 'season_pass_not_found',
    SEASON_PASS_FORBIDDEN = 'season_pass_forbidden',
    SEASON_PASS_HAS_ALLOCATIONS = 'season_pass_has_allocations',
    SALE_INVALID_ALLOCATIONS = 'sale_invalid_allocations',
    SALE_ALLOCATION_PASS_MISMATCH = 'sale_allocation_pass_mismatch',
    IMPORT_CSV_INVALID = 'import_csv_invalid',
    IMPORT_ROWS_INVALID = 'import_rows_invalid',
    IMPORT_PASSES_MIXED_SEASONS = 'import_passes_mixed_seasons',
    USER_NOT_FOUND = 'user_not_found',
}
